manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: caksoylar
      url-base: https://github.com/caksoylar
    - name: infely
      url-base: https://github.com/infely
    # Additional modules containing boards/shields/custom code can be listed here as well
    # See https://docs.zephyrproject.org/3.2.0/develop/west/manifest.html#projects
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    - name: zmk-rgbled-widget
      remote: caksoylar
      revision: main
    - name: nice-view-battery                  
      remote: infely                           
      revision: main                                
    # - name: ncs-playground
    #   url: https://github.com/makerdiary/ncs-playground
    #   revision: b57066890f7f01e8f38c7ac3fdfff798ad63c1cc
  self:
    path: config
